### ISSUE TITLE
Current testsite local deployment is broken

### ISSUE THREAD

**Issue by knivets** [djaodjin/djaodjin-multitier#5]
Probably python3 and new django version compatibility issue.

<img width="1389" alt="screen shot 2019-01-30 at 17 01 52" src="https://user-images.githubusercontent.com/1903479/51973692-c8031500-24b0-11e9-9e47-f395e3da617a.png">

**Comment by smirolo** [comment]
Investigated. Seems like Django 2.1 related.

**Comment by smirolo** [comment]
Checked that testsite as of commit [797eed8](https://github.com/djaodjin/djaodjin-multitier/commit/797eed83fe9f73b730c5d1c1c79b72cb8b7fa6e9) is good.
